// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {quota} from '../models';

export function CancelOAuth():Promise<void>;

export function Capture(arg1:string,arg2:string,arg3:boolean):Promise<main.CaptureResult>;

export function DeleteAccount(arg1:string):Promise<void>;

export function FinishOAuth(arg1:string,arg2:string,arg3:string):Promise<main.OAuthResult>;

export function GetQuota(arg1:string):Promise<quota.Overview>;

export function GetState():Promise<main.StateView>;

export function KillZCode():Promise<void>;

export function LaunchZCode():Promise<void>;

export function RenameAccount(arg1:string,arg2:string):Promise<void>;

export function Rollback():Promise<void>;

export function StartOAuth(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Use(arg1:string):Promise<main.UseResult>;
