// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelOAuth() {
  return window['go']['main']['App']['CancelOAuth']();
}

export function Capture(arg1, arg2, arg3) {
  return window['go']['main']['App']['Capture'](arg1, arg2, arg3);
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function FinishOAuth(arg1, arg2, arg3) {
  return window['go']['main']['App']['FinishOAuth'](arg1, arg2, arg3);
}

export function GetQuota(arg1) {
  return window['go']['main']['App']['GetQuota'](arg1);
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function KillZCode() {
  return window['go']['main']['App']['KillZCode']();
}

export function LaunchZCode() {
  return window['go']['main']['App']['LaunchZCode']();
}

export function RenameAccount(arg1, arg2) {
  return window['go']['main']['App']['RenameAccount'](arg1, arg2);
}

export function Rollback() {
  return window['go']['main']['App']['Rollback']();
}

export function StartOAuth(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartOAuth'](arg1, arg2, arg3);
}

export function Use(arg1) {
  return window['go']['main']['App']['Use'](arg1);
}
